name: NovaCore
version: 1.0.0
main: com.minestein.novacore.Core

commands:
  youtube:
    description: For YouTubers.
    aliases: [yt]
    usage: /yt <Subcommand> <Argument>
  hub:
    description: For sending to the lobby.
    aliases: [lobby, leave, quit]
    usage: /hub
  join:
    description: For the join team command.
    usage: /join <Team>
  guide:
    description: For getting help.
    usage: /guide

permissions:
  youtube.command:
    description: For the Youtube command.
    default: op